# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Meine erste eigen Jekyll Hallo Welt Seite
tagline:             ganz viele H채채채채sches
url:                 http://bitsfritz.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Felix P.
  url:               http://bitsfritz.github.io
  email:             leiderkeineemail@no-mail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/bitsfritz/bitsfritz.github.io
